### ISSUE TITLE
[Upstream] Investigate why "yarn" exec commands only list out command name

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/cli-testing-library#13]
When using the following code:

```javascript
const c = require('child_process');
a = c.spawn('yarn', ['ts-node', 'test.js'], {shell: true});
a.stdout.on('data', data => console.log(data.toString()));
a.stderr.on('data', data => console.log(data.toString()))
```

It only outputs the following:

```
> yarn run v1.22.17

$ C:\Users\crutchcorn\git\TestingLibrary\cli-testing-library\node_modules\.bin\ts-node
```

And then immediately proceeds to kill the process. While this isn't an issue with `CLI Testing Library`, it does impact our users and should be investigated

**Comment by crutchcorn** [comment]
Update: I think this is actually #10 masquerading in another form. If I re-test this, I get the output when `stderr` logs out and get the expected:

```
> yarn run v1.22.17

$ C:\Users\crutchcorn\git\TestingLibrary\nx\node_modules\.bin\ts-node test.ts

Error: Cannot find module 'C:\Users\crutchcorn\git\TestingLibrary\nx\test.ts'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at main (C:\Users\crutchcorn\git\TestingLibrary\nx\node_modules\ts-node\src\bin.ts:198:14)
    at Object.<anonymous> (C:\Users\crutchcorn\git\TestingLibrary\nx\node_modules\ts-node\src\bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
